image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar <путь к вашему jar файлу> &

build_script:
    - chmod +x gradlew
    - ./gradlew test --info -Dselenide.headless=true